<?php

namespace App\Actions;

use Spatie\Mailcoach\Http\Api\Requests\SendTransactionalMailRequest;
use Spatie\Mjml\Mjml;

class SendTransactionalMailAction extends \Spatie\Mailcoach\Domain\Shared\Actions\SendTransactionalMailAction
{
    public function execute(SendTransactionalMailRequest $request): string
    {
        $mjml = app(Mjml::class)
            ->sidecar()
            ->minify()
            ->toHtml($request->html);

        $request->html = $mjml;

        return parent::execute($request); // TODO: Change the autogenerated stub
    }
}
