<?php

namespace App\Actions;

use Illuminate\Support\Facades\Http;
use Spatie\Mailcoach\Http\Api\Requests\SendTransactionalMailRequest;
use Spatie\Mjml\Mjml;

class SendTransactionalMailAction extends \Spatie\Mailcoach\Domain\Shared\Actions\SendTransactionalMailAction
{
    public function execute(SendTransactionalMailRequest $request): string
    {
        $id = $request->html;

        $message = Http::coeliac()->get("/mailcoach-message/{$id}?key=".config('services.coeliac.key'));

        $request->html = $message->getBody()->getContents();

        return parent::execute($request); // TODO: Change the autogenerated stub
    }
}
